### PR TITLE
Rename package to @idpass/smartshare-react-native

### PR DESCRIPTION
**Pull request by arnellebalane**
### Changes

- Rename references to original name `react-native-idpass-smartshare` to `@idpass/smartshare-react-native` or just `smartshare-react-native` for consistency with other open source ID PASS project names

### CODE REVIEW

**Comment by arnellebalane** [comment]
@typelogic @rjmangubat23 What are your thoughts about renaming the Android package to `org.idpass.smartshare.reactnative` or `org.idpass.smartshare.reactnative`? 😅

**Comment by rjmangubat23** [comment]
> ### Changes
> * Rename references to original name `react-native-idpass-smartshare` to `@idpass/smartshare-react-native` or just `smartshare-react-native` for consistency with other open source ID PASS project names

@arnellebalane  I suggest `@idpass/smartshare-react-native` would be better so that it would be consistent to other projects like for smartscanner for example.

**Comment by arnellebalane** [comment]
@rjmangubat23 Ah yeah this PR already changes them to `@idpass/smartshare-react-native`, except for some cases where I can't use the `@idpass/` prefix then it's just `smartshare-react-native`, e.g. in the iOS Podspec 😅

**Comment by rjmangubat23** [comment]
> @typelogic @rjmangubat23 What are your thoughts about renaming the Android package to `org.idpass.smartshare.reactnative` or `org.idpass.smartshare.reactnative`? 😅

yes I would agree with this unless it will conflict with anthing that is reactnative related, @typelogic what do you think?

**Review by rjmangubat23 — APPROVED** [review]
LGTM. 👍

**Comment by rjmangubat23** [comment]
> @rjmangubat23 Ah yeah this PR already changes them to `@idpass/smartshare-react-native`, except for some cases where I can't use the `@idpass/` prefix then it's just `smartshare-react-native`, e.g. in the iOS Podspec 😅

@arnellebalane ahh yes! sorry! haha I got confused with all the naming. my apologies 😅 but PR looks good to me. Thank you! 🙇

**Review by typelogic — COMMENTED** [review]
I need paolo's use of the library to be as-as, and then this renaming should be fine.

**Comment by typelogic** [comment]
Another test todo is to rebuild the test app, after the rename. The `npx` projection creation naming system could be deeply entangled..

**Comment by arnellebalane** [comment]
@typelogic @rjmangubat23 We can proceed with this renaming of the package
- Paolo's usage of the package is currently based on `react-native-idpass-smartshare@0.1.0` which is the original version published in npm. We won't publish these changes into that package, so they should be unaffected as long as they keep using that. 
- This change we will publish under a new package name under the ID PASS npm org. Future updates to this library will be published into this new package name.
- (Optional) We can mark the original `react-native-idpass-smartshare` package as deprecated
- Paolo can then later on switch to this new package whenever convenient of if they need updates that are published into this new package. The changes required from their code will just be renaming the package they import from into this new package name instead of `react-native-idpass-smartshare`
- Note that this PR only renames the library files that are related or that will affect package publishing. The package names in the Android Java codebase e.g. `com.reactnativeidpasssmartshare` are kept as-is. We can change them in a different PR in the future based on [this comment](https://github.com/idpass/smartshare-react-native/pull/4#issuecomment-1039861741)

Waiting for @typelogic 's approval before merging this PR.

**Comment by typelogic** [comment]
I verified, that the rename to `smartshare-react-native` does not break the `example/` test app. That is, the test run of the `example/` app as described in the README still works after this rename.

**Pull request merged**
